"""
encoding.py

Copyright 2012 Andres Riancho

This file is part of w3af, http://w3af.org/ .

w3af is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation version 2 of the License.

w3af is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with w3af; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

"""

import codecs
import importlib
import logging
import urllib.error
import urllib.parse
import urllib.request
from typing import Any

from w3af.core.data.constants.encodings import DEFAULT_ENCODING

chardet: Any = importlib.import_module("chardet")

# Hiding awful logging messages generated by chardet module when running
# almost any unit test
logging.getLogger("chardet.charsetprober").setLevel(logging.WARNING)

# Custom error handling schemes registration
ESCAPED_CHAR = "slash_escape_char"
PERCENT_ENCODE = "percent_encode"
HTML_ENCODE = "html_encode_char"


def _return_html_encoded(encodingexc):
    """
    :return: &#xff when input is \xff
    """
    st = encodingexc.start
    en = encodingexc.end
    invalid_data = encodingexc.object[st:en]
    if isinstance(invalid_data, bytes):
        hex_encoded = "".join(f"{byte:02x}" for byte in invalid_data)
    else:
        hex_encoded = "".join(f"{ord(char):x}" for char in invalid_data)

    return str("&#x" + hex_encoded), en


def _return_escaped_char(encodingexc):
    """
    :return: \\xff when input is \xff
    """
    st = encodingexc.start
    en = encodingexc.end

    invalid_data = encodingexc.object[st:en]
    if isinstance(invalid_data, bytes):
        slash_x_XX = "".join(f"\\x{byte:02x}" for byte in invalid_data)
    else:
        slash_x_XX = invalid_data.encode("unicode_escape").decode("ascii")
    return str(slash_x_XX), en


def _percent_encode(encodingexc):
    if not isinstance(encodingexc, UnicodeEncodeError):
        raise encodingexc

    st = encodingexc.start
    en = encodingexc.end

    return (urllib.parse.quote(encodingexc.object[st:en].encode("utf8")), en)


codecs.register_error(ESCAPED_CHAR, _return_escaped_char)
codecs.register_error(PERCENT_ENCODE, _percent_encode)
codecs.register_error(HTML_ENCODE, _return_html_encoded)


def smart_unicode(s, encoding=DEFAULT_ENCODING, errors="strict", on_error_guess=True):
    """
    Return the unicode representation of 's'. Decodes byte-strings using
    the 'encoding' codec, falling back to the encoding chardet guesses when
    on_error_guess is set.
    """
    if isinstance(s, str):
        return s

    if not isinstance(s, bytes):
        return str(s)

    try:
        return s.decode(encoding, errors)
    except UnicodeDecodeError:
        if not on_error_guess:
            raise

    guessed_encoding = chardet.detect(s)["encoding"]
    if guessed_encoding is None:
        # Chardet failed to guess the encoding! This is really broken
        return s.decode(encoding, "ignore")

    try:
        return s.decode(guessed_encoding, errors)
    except UnicodeDecodeError:
        return s.decode(encoding, "ignore")


def smart_str(s, encoding=DEFAULT_ENCODING, errors="strict"):
    """
    Return a byte-string version of 's', encoded as specified in 'encoding'.
    Objects are converted with str() first; when that fails and errors is not
    'strict' an empty byte-string is returned.
    """
    if isinstance(s, bytes):
        return s

    if not isinstance(s, str):
        try:
            s = str(s)
        except UnicodeEncodeError:
            if errors == "strict":
                raise
            return b""

    return s.encode(encoding, errors)


def smart_str_ignore(s, encoding=DEFAULT_ENCODING):
    return smart_str(s, encoding=encoding, errors="ignore")


def is_known_encoding(encoding):
    """
    :return: True if the encoding name is known.

    >>> is_known_encoding('foo')
    False
    >>> is_known_encoding('utf-8')
    True
    """
    try:
        codecs.lookup(encoding)
        return True
    except LookupError:
        return False
