"""
test_cookie_handler.py

Copyright 2012 Andres Riancho

This file is part of w3af, http://w3af.org/ .

w3af is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation version 2 of the License.

w3af is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with w3af; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

"""

import http.cookiejar
import os
import tempfile
import unittest
import urllib.request

from w3af.core.data.parsers.doc.url import URL
from w3af.core.data.url.extended_urllib import ExtendedUrllib
from w3af.core.data.url.handlers.cookie_handler import CookieHandler
from w3af.core.data.url.http_request import HTTPRequest
from w3af.core.data.url.tests.helpers.route_server import (
    RecordedRequest,
    Response,
    RouteServer,
)

SEND_COOKIE_PATH = "/send-cookie"
CHECK_COOKIE_PATH = "/check-cookie"
COOKIE_VALUE = "session=123456789"

COOKIEJAR = """\
    # Netscape HTTP Cookie File
    # Generated by Wget on 2013-05-11 17:16:04.
    # Edit at your own risk.

    127.0.0.1\tFALSE\t/\tFALSE\t2736616305\tsession\t123456789
    """


def check_expected_cookie(request: RecordedRequest) -> Response:
    if request.headers.get("cookie") == COOKIE_VALUE:
        return Response(body="Cookie received")
    return Response(body="Cookie not sent")


def echo_received_cookie(request: RecordedRequest) -> Response:
    received_cookie_value = request.headers.get("cookie")
    if received_cookie_value is not None:
        return Response(body=f"Cookie {received_cookie_value} received")
    return Response(body="Cookie not sent")


class TestCookieHandler(unittest.TestCase):

    def setUp(self):
        self.server = RouteServer()
        self.server.add(
            "GET", SEND_COOKIE_PATH, Response(headers=[("Set-Cookie", COOKIE_VALUE)])
        )
        self.server.add("GET", CHECK_COOKIE_PATH, check_expected_cookie)
        self.server.start()

        self.url_send_cookie = URL(self.server.url(SEND_COOKIE_PATH))
        self.url_check_cookie = URL(self.server.url(CHECK_COOKIE_PATH))

    def tearDown(self):
        self.server.stop()

    def open_check_cookie(self, opener, cookies):
        request = HTTPRequest(self.url_check_cookie, cookies=cookies)
        return opener.open(request).read()

    def test_low_level(self):
        opener = urllib.request.build_opener(CookieHandler)

        # With this request the CookieHandler should store a cookie in its
        # cookiejar
        opener.open(HTTPRequest(self.url_send_cookie)).read()

        # And now it will send it because we're setting cookie to True
        self.assertIn(b"Cookie received", self.open_check_cookie(opener, True))

        # And now it will NOT send any cookie because we're setting cookie to False
        self.assertIn(b"Cookie not sent", self.open_check_cookie(opener, False))

        # And now it will send it because we're setting cookie to True
        self.assertIn(b"Cookie received", self.open_check_cookie(opener, True))

    def test_low_level_with_cookie_jar(self):
        # IMPORTANT NOTE: Please remember that the cookie expiration, 2736616305
        # above, is going to limit the date until which this unittest will PASS

        # Remove all the indent and save the cookiejar
        cj_contents = COOKIEJAR.replace(" " * 4, "")
        with tempfile.NamedTemporaryFile("w", delete=False) as tmp_file:
            tmp_file.write(cj_contents)
        self.addCleanup(os.unlink, tmp_file.name)

        cj = http.cookiejar.MozillaCookieJar()
        cj.load(tmp_file.name, ignore_discard=True, ignore_expires=True)

        opener = urllib.request.build_opener(CookieHandler(cj))

        # Verify cookie from cookie jar is sent
        self.assertIn(b"Cookie received", self.open_check_cookie(opener, True))

        # And now it will NOT send any cookie because we're setting cookie to False
        self.assertIn(b"Cookie not sent", self.open_check_cookie(opener, False))

    def test_xurllib(self):
        uri_opener = ExtendedUrllib()
        self.addCleanup(uri_opener.end)
        uri_opener.GET(self.url_send_cookie)

        resp = uri_opener.GET(self.url_check_cookie, cookies=True)
        self.assertIn("Cookie received", resp)

        resp = uri_opener.GET(self.url_check_cookie, cookies=False)
        self.assertIn("Cookie not sent", resp)

        resp = uri_opener.GET(self.url_check_cookie, cookies=True)
        self.assertIn("Cookie received", resp)

    def test_sessions_basic(self):
        uri_opener = ExtendedUrllib()
        self.addCleanup(uri_opener.end)
        session_1 = uri_opener.get_new_session()
        session_2 = uri_opener.get_new_session()

        uri_opener.GET(self.url_send_cookie, session=session_1)

        resp = uri_opener.GET(self.url_check_cookie, cookies=True, session=session_1)
        self.assertIn("Cookie received", resp)

        resp = uri_opener.GET(self.url_check_cookie, cookies=True, session=session_2)
        self.assertIn("Cookie not sent", resp)

    def test_sessions_simultaneous(self):
        self.server.add(
            "GET",
            SEND_COOKIE_PATH + "1",
            Response(headers=[("Set-Cookie", "11111111")]),
        )
        self.server.add(
            "GET",
            SEND_COOKIE_PATH + "2",
            Response(headers=[("Set-Cookie", "222222222")]),
        )
        self.server.add("GET", CHECK_COOKIE_PATH, echo_received_cookie)

        uri_opener = ExtendedUrllib()
        self.addCleanup(uri_opener.end)
        session_1 = uri_opener.get_new_session()
        session_2 = uri_opener.get_new_session()

        uri_opener.GET(URL(self.server.url(SEND_COOKIE_PATH + "1")), session=session_1)
        uri_opener.GET(URL(self.server.url(SEND_COOKIE_PATH + "2")), session=session_2)

        resp = uri_opener.GET(self.url_check_cookie, session=session_1)
        self.assertIn("Cookie 11111111 received", resp.body)

        resp = uri_opener.GET(self.url_check_cookie, session=session_2)
        self.assertIn("Cookie 222222222 received", resp)
