"""
test_profile_composer.py

This file is part of w3af, http://w3af.org/ .

w3af is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation version 2 of the License.

w3af is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with w3af; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

"""

import configparser
import unittest

from w3af.core.ui.api.utils.profile_composer import compose_profile, split_sections

PROFILE = """; generated by w3af
[profile]
name = custom
description = A custom profile

[audit.xss]
persistent_xss = True

[audit.sqli]

[crawl.web_spider]
only_forward = True

[grep.html_comments]

[misc-settings]
max_discovery_time = 20
"""


def parse(profile_text):
    config = configparser.ConfigParser(interpolation=None, strict=False)
    config.read_string(profile_text)
    return config


class ProfileComposerTest(unittest.TestCase):
    def test_split_sections_keeps_every_line(self):
        sections = split_sections(PROFILE)

        self.assertIsNone(sections[0].name)
        self.assertEqual(sections[0].lines, ["; generated by w3af"])
        self.assertEqual(
            [section.name for section in sections[1:]],
            [
                "profile",
                "audit.xss",
                "audit.sqli",
                "crawl.web_spider",
                "grep.html_comments",
                "misc-settings",
            ],
        )
        lines = [line for section in sections for line in section.lines]
        self.assertEqual(lines, PROFILE.splitlines())

    def test_enables_exactly_the_selected_plugins_of_managed_types(self):
        composed = parse(
            compose_profile(PROFILE, {"audit": ["xss", "os_commanding"], "grep": []})
        )

        self.assertEqual(
            composed.sections(),
            [
                "profile",
                "audit.xss",
                "crawl.web_spider",
                "misc-settings",
                "audit.os_commanding",
            ],
        )
        self.assertEqual(composed.get("audit.xss", "persistent_xss"), "True")
        self.assertEqual(composed.get("crawl.web_spider", "only_forward"), "True")
        self.assertEqual(composed.get("misc-settings", "max_discovery_time"), "20")
        self.assertEqual(composed.get("profile", "name"), "custom")

    def test_adds_a_profile_section_when_missing(self):
        composed_text = compose_profile("", {"crawl": ["web_spider"]})
        composed = parse(composed_text)

        self.assertEqual(composed.sections(), ["profile", "crawl.web_spider"])
        self.assertEqual(composed.get("profile", "name"), "web_ui")
        self.assertTrue(composed_text.endswith("[crawl.web_spider]\n"))

    def test_sections_without_plugin_type_are_kept(self):
        composed = parse(compose_profile("[target]\ntarget = x\n", {"target": []}))
        self.assertEqual(composed.sections(), ["profile", "target"])
