from collections.abc import Callable
from typing import Any

class Node:
    fields: list[str]
    lineno: int | None
    def __init__(self, *args: Any, lineno: int | None = None) -> None: ...
    def accept(self, visitor: Callable[[Node], object]) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

def node(name: str, fields: list[str]) -> type[Node]: ...

class Block(Node): ...
class Assignment(Node): ...
class Echo(Node): ...
class Print(Node): ...
class Include(Node): ...
class Require(Node): ...
class FunctionCall(Node): ...
class Variable(Node): ...
class ArrayOffset(Node): ...
class If(Node): ...
class ElseIf(Node): ...
class Else(Node): ...
class While(Node): ...
class DoWhile(Node): ...
class For(Node): ...
class Foreach(Node): ...
