from collections.abc import Hashable, Iterator, Sequence

class KeywordTree:
    def __init__(self, case_insensitive: bool = False) -> None: ...
    def add(self, keyword: Sequence[Hashable]) -> None: ...
    def finalize(self) -> None: ...
    def search(
        self, text: Sequence[Hashable]
    ) -> tuple[Sequence[Hashable], int] | None: ...
    def search_all(
        self, text: Sequence[Hashable]
    ) -> Iterator[tuple[Sequence[Hashable], int]]: ...
